# Generated by Django 2.2.4 on 2021-01-16 03:49

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowed_to_work',
            field=models.BooleanField(default=False, verbose_name='Allowed to work in US'),
        ),
        migrations.AddField(
            model_name='profile',
            name='field_of_study',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Field of study '),
        ),
        migrations.AddField(
            model_name='profile',
            name='hours_per_week',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(168), django.core.validators.MinValueValidator(0)], verbose_name='Hours available per week'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pay_margin_max',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum pay'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pay_margin_min',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum pay'),
        ),
        migrations.AddField(
            model_name='profile',
            name='services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None, verbose_name='Relevant skills'),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Name of university '),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_type',
            field=models.CharField(blank=True, choices=[('part_time', 'Part Time'), ('full_time', 'Full Time Project'), ('remote', 'Remote'), ('one_time', 'One Time Project'), ('ongoing_project', 'Ongoing Project')], default=None, max_length=15, null=True, verbose_name='Work Type'),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(0)], verbose_name='Years of experience'),
        ),
    ]
