# Generated by Django 2.2.4 on 2021-01-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_profile', '0003_profile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate Students “u/s”'), ('graduate', 'Undergraduate Students “u/s”'), ('international', 'International Students “i/s”'), ('companies', 'Companies “c”'), ('start_up', 'Start-ups “s”')], default=None, max_length=15, null=True, verbose_name='Profile Type'),
        ),
    ]
