# Generated by Django 2.2.4 on 2021-01-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_profile', '0004_profile_profile_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pay_margin_max',
            new_name='max_pay',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='pay_margin_min',
            new_name='min_pay',
        ),
    ]
