# Generated by Django 2.2.17 on 2021-02-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_profile', '0008_populatedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_profiles', to='chat_profile.Profile'),
        ),
    ]
