# Generated by Django 2.2.17 on 2021-02-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_profile', '0009_profile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='industry',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
