# Generated by Django 2.2.19 on 2021-04-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_profile', '0012_auto_20210217_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
