# Generated by Django 2.2.4 on 2021-01-18 22:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_profile', '0002_auto_20210116_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default=None, max_length=15, null=True, verbose_name='Experience levels')),
                ('time_frame', models.CharField(blank=True, max_length=150, null=True)),
                ('field', models.CharField(blank=True, max_length=150, null=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorite_jobs', to='chat_profile.Profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='chat_profile.Profile')),
            ],
        ),
    ]
