# Generated by Django 2.2.4 on 2021-01-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='time_frame',
        ),
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='job',
            name='hours_per_week',
            field=models.IntegerField(blank=True, null=True, verbose_name='Availability'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.CharField(blank=True, choices=[('service', 'Service'), ('project', 'Project')], default=None, max_length=15, null=True, verbose_name='Job category'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('part_time', 'Part-time'), ('full_time', 'Full-time'), ('remote', 'Remote'), ('one_time', 'One-time Project'), ('ongoing_project', 'Ongoing Project')], default=None, max_length=17, null=True, verbose_name='Job type'),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_per_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
