# Generated by Django 2.2.17 on 2021-03-02 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_populate_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='budget_type',
            field=models.CharField(blank=True, choices=[('fixed_price', 'Fixed Price'), ('per_hour', 'Per Hour'), ('negotiable', 'Negotiable')], default=None, max_length=17, null=True, verbose_name='Budget type'),
        ),
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.CharField(blank=True, choices=[('less_than_two_weeks', 'Less than 2 weeks'), ('two_to_four_weeks', '2 to 4 weeks'), ('more_than_four_weeks', 'More than 4 weeks')], default=None, max_length=17, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='job',
            name='fixed_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fixed price'),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='USA', max_length=150),
        ),
        migrations.AddField(
            model_name='job',
            name='max_pay',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum pay'),
        ),
        migrations.AddField(
            model_name='job',
            name='min_pay',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum pay'),
        ),
        migrations.AddField(
            model_name='job',
            name='people',
            field=models.IntegerField(blank=True, null=True, verbose_name='Candidates required'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='time',
            field=models.CharField(blank=True, choices=[('less_than_10_hours', 'Less than 10 hours/week'), ('ten_to_twenty_hours', '10-20 hours/week'), ('more_than_four_weeks', 'More than 20 hours/week')], default=None, max_length=17, null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
