# Generated by Django 2.2.17 on 2021-03-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20210302_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='job',
            name='time',
            field=models.CharField(blank=True, choices=[('less_than_10_hours', 'Less than 10 hours/week'), ('ten_to_twenty_hours', '10-20 hours/week'), ('more_than_twenty_hours', 'More than 20 hours/week')], default=None, max_length=150, null=True, verbose_name='Time'),
        ),
    ]
