# Generated by Django 2.2.19 on 2021-04-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_profile', '0013_auto_20210407_1205'),
        ('job', '0009_update_populated_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied',
            field=models.ManyToManyField(blank=True, related_name='applied_jobs', to='chat_profile.Profile'),
        ),
    ]
