# Generated by Django 2.2.17 on 2021-02-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
