# Generated by Django 2.2.18 on 2021-03-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_popuplateusers2'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='profiles',
            field=models.ManyToManyField(related_name='medias', to='user_profile.Profile'),
        ),
    ]
