# Generated by Django 2.2.18 on 2021-03-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_popuplateusers2'),
        ('media', '0002_media_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='deleted',
            field=models.ManyToManyField(related_name='deleted_medias', to='user_profile.Profile'),
        ),
    ]
