# Generated by Django 2.2.17 on 2021-01-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201111_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate Students “u/s”'), ('graduate', 'Undergraduate Students “u/s”'), ('international', 'International Students “i/s”'), ('companies', 'Companies “c”'), ('start_up', 'Start-ups “s”')], default=None, max_length=15, null=True, verbose_name='User Type'),
        ),
    ]
